### ISSUE TITLE
[Mod Incompatability] - Cosmetic Armor breaks Twilight Forest's Charms of Keeping

### ISSUE THREAD

**Issue by AriaElidove** [zlainsama/CosmeticArmorReworked#111]
[1.20.6] - After doing some testing with Cosmetic Armor and Twilight Forest's Charm of Keeping, I have found that when the two mods are installed together, items are completely wiped from a user's inventory whenever a Charm of Keeping has been used. The only items that are not cleared are those within Cosmetic Armor slots (Except for a CoK1, which will drop JUST cosmetic armour).

This has been reported on Twilight Forest's end as well.

**Comment by AriaElidove** [comment]
See Here: https://github.com/TeamTwilight/twilightforest/issues/2162

**Comment by zlainsama** [comment]
After some testing, I think this has nothing to do with my mod. (And by the way, I don't think Twilight Forest's charms ever cared about additional slots in Cosmetic Armor Reworked)
The issue of items disappearing happens even with only Twilight Forest installed in 1.20.6 NeoForge.
It is due to an error happened during Twilight Forest's handling of the PlayerDeath event in their CharmEvents.
You can observe the error with a '/kill' command, as you execute the command an error message will appear in chat and if you look into the log file, you can see the detail of it.

**Comment by AriaElidove** [comment]
> And by the way, I don't think Twilight Forest's charms ever cared about additional slots in Cosmetic Armor Reworked

This seems accurate; 1.20.4 had a similar issue with not keeping cosmetic armours on a player on-death (found initially before reporting the 1.20.6 issue lol). I'm surprised that Cosmetic Armor slots aren't viewn as curios or vanilla armor slots by Twilight Forest, which both *do* work with the CoK's (hah, coks)
